apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: contactbook
  name: contactbook
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32080
  selector:
    app: contactbook
  type: NodePort
status:
  loadBalancer: {}
